- hosts: all
  become: true
  tasks:
  - name: Adding the openstack.example.com domain
    lineinfile:
      path: /etc/hosts
      regexp: '^172\.28\.1\.49\s*openstack\.example\.com.*$'
      line: '172.28.1.49 openstack.example.com'

